-- Migration 011: Health Summaries Table
-- Stores AI-generated weekly health summaries for both 'user' and 'doctor' roles.
-- Summaries are generated by cron from wearable vitals + lab data via the Gemini LLM.

-- ── 1. Create health_summaries table ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS health_summaries (
    id              UUID            PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID            NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    period_type     TEXT            NOT NULL DEFAULT 'weekly',
    target_role     TEXT            NOT NULL CHECK (target_role IN ('user', 'doctor')),
    summary_content TEXT            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMENT ON TABLE health_summaries IS
'AI-generated periodic health summaries. Each row is one summary for a specific
 user and target audience (patient-facing "user" or physician-facing "doctor").';

COMMENT ON COLUMN health_summaries.period_type IS
'Aggregation period: "weekly" (default). Future: "monthly", "quarterly".';

COMMENT ON COLUMN health_summaries.target_role IS
'"user" = plain-language wellbeing summary for the patient.
 "doctor" = clinical summary for the assigned physician.';

-- ── 2. Indexes ───────────────────────────────────────────────────────────────

-- Primary lookup: fetch the most recent summaries for a user + role.
CREATE INDEX IF NOT EXISTS idx_health_summaries_user_role_created
    ON health_summaries (user_id, target_role, created_at DESC);

-- ── 3. Automated retention: delete summaries older than 1 year ───────────────
-- pg_cron must already be enabled (done in migration 010).

SELECT cron.schedule(
    'purge-stale-health-summaries',            -- job name
    '0 5 * * 0',                               -- every Sunday at 05:00 UTC
    $$DELETE FROM public.health_summaries
      WHERE created_at < NOW() - INTERVAL '1 year'$$
);

COMMENT ON EXTENSION pg_cron IS
'Scheduled job "purge-stale-health-summaries" removes summaries older than 1 year.';

-- ── 4. Row Level Security ────────────────────────────────────────────────────

ALTER TABLE health_summaries ENABLE ROW LEVEL SECURITY;

-- Patients can read their own user-facing summaries.
CREATE POLICY "Patients can view own user summaries"
    ON health_summaries FOR SELECT
    USING (
        auth.uid() = user_id
        AND target_role = 'user'
    );

-- Doctors can read doctor-facing summaries for their mapped patients.
CREATE POLICY "Doctors can view patient doctor summaries"
    ON health_summaries FOR SELECT
    USING (
        target_role = 'doctor'
        AND EXISTS (
            SELECT 1 FROM doctor_patient_mapping dpm
            WHERE dpm.doctor_id = auth.uid()
              AND dpm.patient_id = health_summaries.user_id
        )
    );

-- Service-role inserts (backend cron uses the service role key which bypasses
-- RLS, but we add an explicit policy for completeness / if RLS force is enabled).
CREATE POLICY "Service role can insert summaries"
    ON health_summaries FOR INSERT
    WITH CHECK (true);
