/* Week 3+5+6 – Alerts page with interactive acknowledge/dismiss + toasts */
"use client";
export const dynamic = "force-dynamic";

import { useState } from "react";
import { CheckCheck, X } from "lucide-react";
import { Card, SeverityBadge, Badge, Section, EmptyState } from "@/components/ui/shared";
import { cn } from "@/lib/utils";
import { useToast } from "@/components/ui/toast";
import { DEMO_ALERTS, DEMO_PATIENTS, Alert } from "@/lib/demo-data";

export default function AlertsPage() {
  const [patientId, setPatientId] = useState("pat-1");
  const [openId, setOpenId] = useState<string | null>(null);
  // Week 5: local mutable state for acknowledged + dismissed
  const [ackIds, setAckIds] = useState<Set<string>>(
    new Set(DEMO_ALERTS.filter((a) => a.acknowledged).map((a) => a.id))
  );
  const [dismissedIds, setDismissedIds] = useState<Set<string>>(new Set());
  const { toast } = useToast();

  const acknowledge = (id: string, title: string) => {
    setAckIds((prev) => new Set([...prev, id]));
    setOpenId(null);
    toast({ title: "Alert acknowledged", description: title, variant: "success" });
  };
  const dismiss = (id: string, title: string) => {
    setDismissedIds((prev) => new Set([...prev, id]));
    setOpenId(null);
    toast({ title: "Alert dismissed", description: title, variant: "info" });
  };

  const allAlerts = DEMO_ALERTS
    .filter((a) => a.patientId === patientId && !dismissedIds.has(a.id))
    .map((a) => ({ ...a, acknowledged: ackIds.has(a.id) }))
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  const alerts = allAlerts;
  const active = alerts.filter((a) => !a.acknowledged);
  const acked = alerts.filter((a) => a.acknowledged);

  return (
    <div className="max-w-3xl mx-auto px-4 py-6 space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-white">Alerts</h1>
        <select
          value={patientId}
          onChange={(e) => setPatientId(e.target.value)}
          className="bg-slate-800 border border-slate-700 text-slate-200 text-sm rounded-lg px-3 py-1.5"
        >
          {DEMO_PATIENTS.map((p) => (
            <option key={p.id} value={p.id}>{p.name}</option>
          ))}
        </select>
      </div>

      {/* Summary bar */}
      <div className="grid grid-cols-3 gap-3 text-center">
        {[
          { label: "Active", count: active.length, color: "text-red-400" },
          { label: "Acknowledged", count: acked.length, color: "text-emerald-400" },
          { label: "Total", count: alerts.length, color: "text-slate-300" },
        ].map(({ label, count, color }) => (
          <div key={label} className="bg-slate-800 border border-slate-700 rounded-xl py-3">
            <p className={`text-2xl font-bold ${color}`}>{count}</p>
            <p className="text-xs text-slate-400 mt-0.5">{label}</p>
          </div>
        ))}
      </div>

      {/* Active alerts */}
      <Section title="Active Alerts" subtitle="Generated by Rules Engine — no AI involved">
        {active.length === 0 ? (
          <EmptyState message="No active alerts." icon={<CheckCheck />} />
        ) : (
          <div className="space-y-3">
            {active.map((a) => (
              <AlertCard
                key={a.id}
                alert={a}
                open={openId === a.id}
                onToggle={() => setOpenId(openId === a.id ? null : a.id)}
                onAcknowledge={() => acknowledge(a.id, a.title)}
                onDismiss={() => dismiss(a.id, a.title)}
              />
            ))}
          </div>
        )}
      </Section>

      {/* Acknowledged */}
      {acked.length > 0 && (
        <Section title="Acknowledged">
          <div className="space-y-2 opacity-60">
            {acked.map((a) => (
              <AlertCard
                key={a.id}
                alert={a}
                open={openId === a.id}
                onToggle={() => setOpenId(openId === a.id ? null : a.id)}
                onDismiss={() => dismiss(a.id, a.title)}
              />
            ))}
          </div>
        </Section>
      )}
    </div>
  );
}

function AlertCard({
  alert,
  open,
  onToggle,
  onAcknowledge,
  onDismiss,
}: {
  alert: Alert;
  open: boolean;
  onToggle: () => void;
  onAcknowledge?: () => void;
  onDismiss?: () => void;
}) {
  const catIcon: Record<string, string> = {
    lab: "🧪",
    sleep: "🌙",
    activity: "🏃",
    environment: "🌍",
    trend: "📈",
  };

  return (
    <Card
      className={cn(
        "space-y-2",
        !alert.acknowledged && alert.severity === "critical" && "border-red-600/70",
        !alert.acknowledged && alert.severity === "high" && "border-red-700/60",
        !alert.acknowledged && alert.severity === "medium" && "border-amber-700/50",
        !alert.acknowledged && alert.severity === "low" && "border-blue-800/40"
      )}
      onClick={onToggle}
    >
      <div className="flex items-start gap-3">
        <span className="text-lg leading-none mt-0.5">{catIcon[alert.category] ?? "⚠️"}</span>
        <div className="flex-1 min-w-0">
          <div className="flex items-center flex-wrap gap-2">
            <p className="text-sm font-semibold text-white">{alert.title}</p>
            <SeverityBadge severity={alert.severity} />
            <Badge variant="outline" className="text-[10px]">{alert.category}</Badge>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">{alert.reason}</p>
        </div>
      </div>

      {open && (
        <div className="pt-1 pl-8 space-y-1">
          <p className="text-xs font-medium text-slate-300 mb-1">Evidence</p>
          {alert.evidence.map((ev, i) => (
            <div key={i} className="flex items-start gap-2">
              <span className="text-blue-400 mt-0.5 text-xs">→</span>
              <p className="text-xs text-slate-300">{ev}</p>
            </div>
          ))}
          <p className="text-[10px] text-slate-500 pt-1">
            {new Date(alert.createdAt).toLocaleString("en-IN")}
          </p>
          {/* Week 5: action buttons */}
          <div className="flex gap-2 pt-2" onClick={(e) => e.stopPropagation()}>
            {onAcknowledge && !alert.acknowledged && (
              <button
                onClick={onAcknowledge}
                className="flex items-center gap-1.5 text-xs bg-emerald-900/40 border border-emerald-700/50 text-emerald-400 hover:bg-emerald-800/50 px-3 py-1.5 rounded-lg transition-colors"
              >
                <CheckCheck size={12} /> Acknowledge
              </button>
            )}
            {onDismiss && (
              <button
                onClick={onDismiss}
                className="flex items-center gap-1.5 text-xs bg-slate-700/60 border border-slate-600 text-slate-400 hover:text-slate-200 hover:bg-slate-700 px-3 py-1.5 rounded-lg transition-colors"
              >
                <X size={12} /> Dismiss
              </button>
            )}
          </div>
        </div>
      )}
    </Card>
  );
}
