/* Chat — Layer 5 (Gemini 2.5 Flash) + Layer 4 (Context Builder) demo */
"use client";

import { useState, useRef, useEffect } from "react";
import { Send, Mic, ExternalLink, ChevronDown, ChevronUp, Database, Wind, Activity } from "lucide-react";
import { Badge } from "@/components/ui/shared";
import { DEMO_CHAT_HISTORY, DEMO_PATIENTS, DEMO_CONTEXT_OBJECT, ChatMessage } from "@/lib/demo-data";
import { cn } from "@/lib/utils";

export default function ChatPage() {
  const [patientId, setPatientId] = useState("pat-1");
  const [messages, setMessages] = useState<ChatMessage[]>(DEMO_CHAT_HISTORY.filter((m) => true));
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [showContext, setShowContext] = useState(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  function handleSend() {
    if (!input.trim()) return;
    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      role: "user",
      content: input.trim(),
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    // Demo: echo a stub answer after 1.2s
    setTimeout(() => {
      const reply: ChatMessage = {
        id: `ai-${Date.now()}`,
        role: "assistant",
        content:
          "This is a demo response. In the full system, this will be generated by Gemini 2.5 Flash using your medical reports, health metrics, and environmental context as grounded evidence.",
        citations: ["[Demo Mode — RAG engine not yet connected]"],
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, reply]);
      setLoading(false);
    }, 1200);
  }

  return (
    <div className="flex flex-col h-screen max-h-screen">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800 bg-slate-900 flex-shrink-0">
        <div>
          <h1 className="text-sm font-bold text-white">AI Health Companion</h1>
          <p className="text-[10px] text-slate-400">Not a doctor · Powered by Gemini 2.5 Flash</p>
        </div>
        <select
          value={patientId}
          onChange={(e) => setPatientId(e.target.value)}
          className="bg-slate-800 border border-slate-700 text-slate-200 text-xs rounded-lg px-2 py-1"
        >
          {DEMO_PATIENTS.map((p) => (
            <option key={p.id} value={p.id}>{p.name}</option>
          ))}
        </select>
      </div>

      {/* Safety notice */}
      <div className="px-4 py-2 bg-amber-900/20 border-b border-amber-800/30 flex-shrink-0">
        <p className="text-[10px] text-amber-400">
          ⚠ This assistant is NOT a doctor. It cannot diagnose or prescribe. Always consult a qualified healthcare professional.
        </p>
      </div>

      {/* Layer 4: Context Builder panel */}
      <div className="flex-shrink-0 border-b border-slate-800 bg-slate-900/80">
        <button
          className="w-full flex items-center justify-between px-4 py-2 text-[11px] text-slate-400 hover:text-slate-300 transition-colors"
          onClick={() => setShowContext((v) => !v)}
        >
          <span className="font-semibold tracking-wide">Layer 4 — Context sent to Gemini</span>
          {showContext ? <ChevronUp size={12}/> : <ChevronDown size={12}/>}
        </button>
        {showContext && (
          <div className="px-4 pb-3 space-y-2 text-[11px]">
            <div className="flex gap-3 flex-wrap">
              <span className="flex items-center gap-1 text-slate-300">
                <Activity size={10} className="text-blue-400"/>
                Steps: <b className="text-white">{DEMO_CONTEXT_OBJECT.userMetrics.steps}</b>
              </span>
              <span className="flex items-center gap-1 text-slate-300">
                🌙 Sleep: <b className="text-white">{DEMO_CONTEXT_OBJECT.userMetrics.sleepHours}h</b>
              </span>
              <span className="flex items-center gap-1 text-slate-300">
                ❤️ HR: <b className="text-white">{DEMO_CONTEXT_OBJECT.userMetrics.heartRateAvg} bpm</b>
              </span>
            </div>
            <div className="flex items-start gap-1">
              <Wind size={10} className="text-emerald-400 mt-0.5 flex-shrink-0"/>
              <span className="text-slate-400">{DEMO_CONTEXT_OBJECT.environmentSummary}</span>
            </div>
            <div className="space-y-1">
              <p className="flex items-center gap-1 text-slate-400"><Database size={10} className="text-purple-400"/> RAG chunks ({DEMO_CONTEXT_OBJECT.ragChunks.length}):</p>
              {DEMO_CONTEXT_OBJECT.ragChunks.map((c) => (
                <div key={c.chunkId} className="flex items-start gap-2 ml-3">
                  <span className="text-purple-400 text-[10px] font-mono">{(c.similarityScore * 100).toFixed(0)}%</span>
                  <p className="text-slate-400 truncate">{c.text.slice(0, 65)}…</p>
                </div>
              ))}
            </div>
            <p className="text-slate-600 font-mono">role: {DEMO_CONTEXT_OBJECT.role} · built: {new Date(DEMO_CONTEXT_OBJECT.builtAt).toLocaleTimeString("en-IN")}</p>
          </div>
        )}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {messages.map((msg) => (
          <MessageBubble key={msg.id} msg={msg} />
        ))}
        {loading && (
          <div className="flex gap-2 items-center">
            <div className="h-8 w-8 rounded-full bg-blue-600/20 border border-blue-600/40 flex items-center justify-center text-xs text-blue-400 font-bold flex-shrink-0">
              AI
            </div>
            <div className="bg-slate-800 rounded-2xl px-4 py-2">
              <TypingIndicator />
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="flex-shrink-0 border-t border-slate-800 px-4 py-3 bg-slate-900">
        <div className="flex items-center gap-2 bg-slate-800 border border-slate-700 rounded-xl px-3 py-2">
          <input
            className="flex-1 bg-transparent text-sm text-slate-100 placeholder:text-slate-500 outline-none"
            placeholder="Ask about your health data…"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && handleSend()}
          />
          <button className="text-slate-500 hover:text-slate-300 transition-colors" title="Voice input (ElevenLabs / Whisper — coming soon)">
            <Mic size={16} />
          </button>
          <button
            onClick={handleSend}
            className={cn(
              "h-7 w-7 rounded-lg flex items-center justify-center transition-colors",
              input.trim() ? "bg-blue-600 text-white hover:bg-blue-500" : "bg-slate-700 text-slate-500 cursor-not-allowed"
            )}
          >
            <Send size={13} />
          </button>
        </div>
      </div>
    </div>
  );
}

function MessageBubble({ msg }: { msg: ChatMessage }) {
  const isUser = msg.role === "user";
  return (
    <div className={cn("flex gap-2", isUser && "flex-row-reverse")}>
      <div
        className={cn(
          "h-8 w-8 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0",
          isUser
            ? "bg-purple-600/30 border border-purple-600/50 text-purple-300"
            : "bg-blue-600/20 border border-blue-600/40 text-blue-400"
        )}
      >
        {isUser ? "U" : "AI"}
      </div>
      <div className={cn("max-w-[80%] space-y-1.5", isUser && "items-end flex flex-col")}>
        <div
          className={cn(
            "rounded-2xl px-4 py-2.5 text-sm leading-relaxed",
            isUser
              ? "bg-purple-600/20 border border-purple-600/30 text-slate-100 rounded-tr-sm"
              : "bg-slate-800 border border-slate-700 text-slate-100 rounded-tl-sm"
          )}
        >
          {msg.content}
        </div>
        {msg.citations && msg.citations.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {msg.citations.map((c, i) => (
              <span
                key={i}
                className="inline-flex items-center gap-1 text-[10px] text-blue-400 bg-blue-900/20 border border-blue-800/40 rounded px-1.5 py-0.5"
              >
                <ExternalLink size={9} />
                {c}
              </span>
            ))}
          </div>
        )}
        <p className="text-[10px] text-slate-600 px-1">
          {new Date(msg.timestamp).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}
        </p>
      </div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div className="flex gap-1 items-center h-4">
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-bounce"
          style={{ animationDelay: `${i * 0.15}s` }}
        />
      ))}
    </div>
  );
}
