"""HTTP routes for fetching and evaluating alerts.

Endpoints
---------
GET /alerts/{user_id}
    Fetch all stored alerts for a user (JWT-protected).

POST /alerts/evaluate/{user_id}
    Run the rules engine for the authenticated user (JWT-protected).

POST /alerts/admin/evaluate/{user_id}
    Run the rules engine for any user — **service-role only**.
    Called by the nightly cron automation script.
"""
import logging

from fastapi import APIRouter, Depends, HTTPException, status

from backend.config.supabase_client import get_supabase_client
from backend.middleware.auth_middleware import get_current_user, verify_service_role

router = APIRouter(prefix="/alerts", tags=["alerts"])
logger = logging.getLogger(__name__)


def _fetch_alert_evidence_rows(client, alert_ids: list[str]) -> list[dict]:
    """Fetch alert evidence with compatibility for older DB schemas."""
    try:
        response = (
            client.table("alert_evidence")
            .select(
                "id, alert_id, report_id, lab_result_id, "
                "ocr_text_snippet, environmental_evidence"
            )
            .in_("alert_id", alert_ids)
            .execute()
        )
        return response.data or []
    except Exception as exc:
        message = str(exc)
        if "environmental_evidence" not in message or "does not exist" not in message:
            raise

        logger.warning(
            "alert_evidence.environmental_evidence is missing; "
            "falling back to legacy evidence query: %s",
            exc,
        )
        fallback = (
            client.table("alert_evidence")
            .select("id, alert_id, report_id, lab_result_id, ocr_text_snippet")
            .in_("alert_id", alert_ids)
            .execute()
        )
        return fallback.data or []


# ---------------------------------------------------------------------------
# GET /alerts/{user_id}  — fetch all alerts for a user
# ---------------------------------------------------------------------------

@router.get("/{user_id}", status_code=status.HTTP_200_OK)
async def get_alerts(user_id: str, include_evidence: bool = True, current_user: str = Depends(get_current_user)):
    if user_id != current_user:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized")
    """Return all alerts stored in the database for a given user.

    Alerts are generated by the deterministic rules engine (run separately
    via ``POST /alerts/evaluate``) and persisted into the ``alerts`` table.

    Query parameters:
    - ``include_evidence`` (default: ``true``) — when true, each alert
      includes its ``evidence`` list from the ``alert_evidence`` table,
      linking the alert back to the specific lab result rows and OCR
      snippets that triggered it.

    Response shape:
    ```json
    {
      "user_id": "...",
      "count": 3,
      "alerts": [
        {
          "id": "...",
          "severity": "high",
          "reason": "...",
          "created_at": "...",
          "evidence": [
            {
              "id": "...",
              "report_id": "...",
              "lab_result_id": "...",
              "ocr_text_snippet": "..."
            }
          ]
        }
      ]
    }
    ```
    """
    client = get_supabase_client()

    # Fetch alerts for this user, most-recent first.
    try:
        alerts_resp = (
            client.table("alerts")
            .select("id, severity, reason, created_at")
            .eq("user_id", user_id)
            .order("created_at", desc=True)
            .execute()
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch alerts: {exc}",
        ) from exc

    alerts = alerts_resp.data or []

    if not alerts:
        return {"user_id": user_id, "count": 0, "alerts": []}

    # Optionally attach evidence rows for each alert.
    if include_evidence:
        alert_ids = [a["id"] for a in alerts]
        try:
            evidence_rows = _fetch_alert_evidence_rows(client, alert_ids)
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to fetch alert evidence: {exc}",
            ) from exc

        # Group evidence rows by alert_id.
        evidence_by_alert: dict[str, list[dict]] = {}
        for ev in evidence_rows:
            aid = ev["alert_id"]
            evidence_by_alert.setdefault(aid, []).append(
                {
                    "id": ev["id"],
                    "report_id": ev.get("report_id"),
                    "lab_result_id": ev.get("lab_result_id"),
                    "ocr_text_snippet": ev.get("ocr_text_snippet"),
                    "environmental_evidence": ev.get("environmental_evidence"),
                }
            )

        for alert in alerts:
            alert["evidence"] = evidence_by_alert.get(alert["id"], [])

    return {"user_id": user_id, "count": len(alerts), "alerts": alerts}


# ---------------------------------------------------------------------------
# Shared evaluation logic (DRY helper — used by both endpoints below)
# ---------------------------------------------------------------------------

def _run_evaluation(user_id: str, location: str | None, date: str | None) -> dict:
    """Shared evaluation logic used by both user and admin endpoints.

    Extracted to satisfy the DRY principle — both routes delegate here.
    """
    client = get_supabase_client()

    try:
        from backend.rules.engine import evaluate_rules
        from backend.rules.inserter import persist_alerts
    except ImportError as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Rules engine not available: {exc}",
        ) from exc

    try:
        alerts = evaluate_rules(client=client, user_id=user_id, location=location, date=date)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Rules evaluation failed: {exc}",
        ) from exc

    try:
        result = persist_alerts(client=client, user_id=user_id, alerts=alerts)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Persisting alerts failed: {exc}",
        ) from exc

    return {
        "user_id": user_id,
        "alerts_triggered": len(alerts),
        "deleted": result.get("deleted", 0),
        "inserted": result.get("inserted", 0),
        "evidence_inserted": result.get("evidence_inserted", 0),
        "errors": result.get("errors", []),
    }


# ---------------------------------------------------------------------------
# POST /alerts/evaluate/{user_id}  — run rules engine (JWT-protected)
# ---------------------------------------------------------------------------

@router.post("/evaluate/{user_id}", status_code=status.HTTP_200_OK)
async def evaluate_alerts(user_id: str, location: str | None = None, date: str | None = None, current_user: str = Depends(get_current_user)):
    """Run the deterministic rules engine for the authenticated user.

    Fetches all lab results for the user from ``lab_results`` (joined via
    ``medical_reports``), evaluates all 13 rules, deletes any previously
    stored alerts for the user, and inserts the new results.

    The operation is **idempotent** — re-running replaces old alerts.

    Returns a summary of what was stored.
    """
    if user_id != current_user:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized")
    return _run_evaluation(user_id, location, date)


# ---------------------------------------------------------------------------
# POST /alerts/admin/evaluate/{user_id}  — service-role only (cron / admin)
# ---------------------------------------------------------------------------

@router.post(
    "/admin/evaluate/{user_id}",
    status_code=status.HTTP_200_OK,
    summary="Run rules engine for a user (service-role only)",
)
async def admin_evaluate_alerts(
    user_id: str,
    location: str | None = None,
    date: str | None = None,
    _authorized: bool = Depends(verify_service_role),
):
    """Service-role-protected evaluation endpoint for the nightly cron job.

    Identical to ``POST /alerts/evaluate/{user_id}`` but secured via the
    ``SUPABASE_SERVICE_ROLE_KEY`` instead of a user JWT.  This allows the
    cron script to evaluate rules for *any* patient without impersonation.
    """
    return _run_evaluation(user_id, location, date)
